language: node_js

node_js: lts/*

cache:
  directories:
    - "$HOME/.npm"

jobs:
  include:
    - stage: Produce Coverage
      node_js: lts/*
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
